steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/my-go-app:latest', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['docker', 'push', 'gcr.io/${PROJECT_ID}/my-go-app:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'container', 'clusters', 'get-credentials', 'my-cluster',
        '--zone', 'us-central1-a', '--project', '${PROJECT_ID}'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'kubectl', 'set', 'image', 'deployment/my-go-app',
        'my-go-app=gcr.io/${PROJECT_ID}/my-go-app:latest'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['kubectl', 'apply', '-f', 'k8s/deployment.yaml']

images:
  - 'gcr.io/${PROJECT_ID}/my-go-app:latest'
